image: debian/stable
packages:
  - findutils
  - build-essential
  - luajit
  - lua5.1
  - lua5.2
  - lua5.3
  - lua5.4
  - pandoc
  - epubcheck
  - poppler-utils
  - gawk
  - texlive-latex-base
  - texlive-fonts-recommended
  - texlive-fonts-extra
  - texlive-latex-extra
sources:
  - https://git.sr.ht/~shakna/jstack
tasks:
  - prep_luau:
      git clone https://github.com/luau-lang/luau
      cd luau-lang
      make config=release luau luau-analyze
  - test: |
      cd jstack
      make -j$(nproc) EXTRA_TARGET=../luau-lang/luau
  - testdoc: |
      cd jstack/book
      make book.pdf
