image: debian/stable
packages:
  - findutils
  - build-essential
  - luajit
  - lua5.1
  - lua5.2
  - lua5.3
  - lua5.4
  - pandoc
  - epubcheck
  - poppler-utils
  - gawk
  - texlive-latex-base
  - texlive-fonts-recommended
  - texlive-fonts-extra
  - texlive-latex-extra
sources:
  - https://git.sr.ht/~shakna/jstack
  - https://github.com/luau-lang/luau
artifacts:
  - jstack/jstack-release.tar.gz
tasks:
  - prep_luau: |
      cd luau
      make config=release luau luau-analyze
  - test: |
      cd jstack
      make -j $(nproc)
  - test_luau: |
      cd jstack
      make EXTRA_TARGET=./$(realpath ../luau/luau)
  - testdoc: |
      cd jstack/book
      make book.pdf
  - release: |
      cd jstack
      bash release.sh
